[package]
name = "ryot_compass"
version = "0.1.0"
edition = "2021"

[dependencies]
ryot = { version = "0.1.0", path = "../ryot" }
bevy = "0.12"
#bevy_egui = "0.22.0"
#egui = { version = "0.23.0", default-features = false, features = ["bytemuck"] }
rand = "0.8.5"
serde = "1.0.193"
async-std = "1.12.0"
rayon = "1.8.0"
log = "0.4.20"
time-test = "0.2.3"
heed = { version = "0.20.0-alpha.9", features = ["serde-rmp"] }
zstd = "0.13.0"
postcard = { version = "1.0.8", features = ["alloc"] }
bytes = "1.5.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3