[package]
name = "ryot"
version = "0.1.0"
edition = "2021"

opt-level = 2

[dependencies]
#arrow2 = { version = "0.18.0", features = ["io_parquet", "io_parquet_compression"] }
#bevy = "0.11.3"
#bevy_egui = "0.22.0"
#bevy_ecs_tilemap = "0.11.1"
#egui = { version = "0.23.0", default-features = false, features = ["bytemuck"] }
#big-brain = { version = "0.18.0"}
#big-brain = { git = "https://github.com/zkat/big-brain.git", branch = "main" }
directories-next = "2.0"
#moonshine-behavior = "0.1.1"
#pathfinding = "4.4.0"
clap = { version = "4.4.10", features = ["derive"] }
rand = "0.8.5"
once_cell = "1.18.0"
serde = "1.0.193"
uuid = "1.6.1"
async-std = "1.12.0"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["macros", "rt", "fs", "io-util"] }
tokio-util = { version = "0.7.1", features = ["compat"] }
futures = "0.3.29"
log = "0.4.20"
rayon = "1.8.0"
chrono = "0.4.31"
#parquet2 = "0.17.2"
#rusty-leveldb = { version = "3.0.0", features = ["async"] }
time-test = "0.2.3"
heed = { version = "0.20.0-alpha.9", features = ["serde-rmp"] }
snap = "1.1.1"
zstd = "0.13.0"
anyhow = { version = "1.0.75", features = [] }
postcard = { version = "1.0.8", features = ["alloc"] }
bytes = "1.5.0"