[directories]
source_path = "ryot_compass/assets/cip-catalog"
destination_path = "ryot_compass/assets"

[sprite_sheet]
sheet_size = [384, 384]
compression_config = { compressed_header_size = 32, content_header_size = 122 }
encoding_config = { vertically_flipped = true, reversed_r_b_channels = true }
