[package]
name = "ryot_internal"
version = "0.2.0"
edition = "2021"
authors = [
    "Lucas Grossi <lucas.ggrosis@gmail.com>",
    "Luan Santos <cargo@luan.sh>",
]
license = "MIT OR Apache-2.0"
description = "An internal Ryot crate used to facilitate optional dynamic linking via the 'dynamic_linking' feature"
homepage = "https://github.com/opentibiabr/Ryot"
repository = "https://github.com/opentibiabr/Ryot"
documentation = "https://docs.rs/ryot/"
keywords = ["gamedev", "assets", "ryot", "otbr", "bevy"]
categories = ["game-development", "game-engines"]

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--cfg", "docsrs"]
all-features = true

[features]
debug = [
    "ryot_grid/debug",
]

compression = ["ryot_core/compression"]

tiled = ["ryot_pathfinder?/tiled"]

[dependencies]
ryot_assets = { path = "../ryot_assets", version = "0.2.0" }
ryot_core = { path = "../ryot_core", version = "0.2.0" }
ryot_grid = { path = "../ryot_grid", version = "0.2.0" }
ryot_legacy_assets = { path = "../ryot_legacy_assets", version = "0.2.0", optional = true }
ryot_pathfinder = { path = "../ryot_pathfinder", version = "0.2.0", optional = true }

