name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  SKIP_BUILD_SCRIPT: true

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - name: Install Linux Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends -y libasound2-dev libudev-dev libgtk-3-dev
        if: runner.os == 'linux'
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - name: Compile
        run: cargo test --all-features --no-run --locked
      - name: Test
        run: cargo test --all-features -- --nocapture --quiet
  all-doc-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Install dependencies
        run: sudo apt-get install -y libgtk-3-dev protobuf-compiler
      - uses: Swatinem/rust-cache@v2
      - name: Run doc tests with all features (this also compiles README examples)
        run: cargo test --doc --all-features --locked -- --nocapture --quiet
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Install dependencies
        run: sudo apt-get install -y libgtk-3-dev protobuf-compiler
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: cargo clippy --workspace --all-targets --all-features -- -Dwarnings
      - name: Check format
        run: cargo fmt --all -- --check
